name: Clippy and test

on:
  push:
    branches:
      - main

env:
  TARGET: aarch64-unknown-linux-gnu

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.77.2-x86_64-unknown-linux-gnu
          target: ${{ env.TARGET }}
          override: true

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: clippy
          args: --target ${{ env.TARGET }}

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Prepare toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.77.2-x86_64-unknown-linux-gnu
          target: ${{ env.TARGET }}
          override: true

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{ env.TARGET }}
